### ISSUE TITLE
Fix smform

### ISSUE THREAD

**Issue by cahans** [OVivero/mimoToolbox#2]
The function to find the Smith-McMillan form uses old matlab functionalities that are not supported any longer. Therefore it needs to be updated to work with a version of Matlab 2015b or newer.

Some changes that need to be made:
- `S=maple('smith',P,p);` should be replaced by `smithForm(P, p);`
- The error that is caused by the expression `d1(k)=lcm(factor(d(i)),factor(d(i-1)));` needs to be resolved

## Definition of done
- Function is working with the example in the documentation

**Comment by OVivero** [comment]
Should be fixed now.

**Comment by cahans** [comment]
Thanks for fixing it. I just tried the example in the documentation, i.e., 
```matlab
    g11=tf([1 0],conv(conv([1 1],[1 1]),conv([1 2],[1 2])));
    g12=tf(conv([1 0],conv([1 1],[1 1])),conv(conv([1 1],[1 1]),conv([1 2],[1 2])));
    g21=tf(-conv([1 0],conv([1 1],[1 1])),conv(conv([1 1],[1 1]),conv([1 2],[1 2])));
    g22=tf(-conv([1 0],conv([1 1],[1 1])),conv(conv([1 1],[1 1]),conv([1 2],[1 2])));
    G=[g11 g12; g21 g22];
    [M,poles,zeros]=smform(G)
```
with `Matlab 2015b` and get the following error.
```
Error using mupadengine/feval (line 163)
Cannot convert the matrix entries to integers or univariate polynomials.

Error in smithForm (line 102)
      Usym = feval(symengine,'symobj::smithForm',A,x);

Error in smform
```

Do you know if this is caused by the old `Matlab 2015b` version, or does the error persist for more recent versions of Matlab?

**Comment by OVivero** [comment]
I wouldn't really know, I had Matlab 2011b until recently and now I updated
straight to 2017a. I don't have the control toolbox at the moment, but if I
input all g's as symbolic it works ok.

Dr. Oskar Vivero

Control Systems Centre
School of Electrical and Electronic Engineering
The University of Manchester
United Kingdom

**Comment by FahadRazaKhan** [comment]
Thank you Dr. Vivero for this wonderful MIMO library. I am trying to get Smith-Mcmillan form of a non-square TFM, however, it is throwing me the following error "Error using mupadengine/feval_internal (line 172)
Square matrix expected."
I am using Matlab 2019b.
